os:
 - linux
 - osx

env:
  - DB=mysql
  - DB=sqlite
  - DB=postgresql

install:
 - export PATH=$PATH:~/Library/Python/2.7/bin
 - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "mysql" ]]; then brew update > /dev/null; fi
 - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "mysql" ]]; then brew install mysql && mysql.server start; fi
 - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "sqlite" ]]; then brew install sqlite; fi
 - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "sqlite" ]]; then export SQLITE3=/usr/local/opt/sqlite/bin/sqlite3; else export SQLITE3=sqlite3; fi
 - if [[ $TRAVIS_OS_NAME == "osx" ]]; then export SILENT=--silent; fi
 - if [[ $TRAVIS_OS_NAME == "osx" ]]; then export YEARMO=$(date -v-6m  +"%Y-%m"); fi
 - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export YEARMO=$(date --date="6 months ago" +"%Y-%m"); fi
 - if [[ $DB == "mysql" ]]; then export USER=root; fi
 - if [[ $DB == "postgresql" ]]; then export USER=postgres; fi
 - make install

before_script:
 - which $SQLITE3 || echo
 - $SQLITE3 -version || echo
 - mysql --version || echo
 - psql --version || echo
 - echo $YEARMO

# Broken up like this because travis chokes on the long delete list
# The --silent flags are because travis's on the huge log
# Touch some of the targets because all the downloading is boring
script:
 - make -j2 --silent sales/raw/2004-{bronx,brooklyn,manhattan,queens,statenisland}.xls
 - make -j2 sales/raw/2008-{bronx,brooklyn,manhattan,queens,statenisland}.xls
 - make -j2 --silent sales/raw/2012-{bronx,brooklyn,manhattan,queens,statenisland}.xls
 - make -j2 sales/raw/20{04,08,12}-{bronx,brooklyn,manhattan,statenisland,queens}.csv
 - make $DB $SILENT USER=$USER PASSFLAG= YEARS="2008 2012" SQLITE=$SQLITE3
 - make YEARS="2004 2008 2012"
 - make -j2 --silent summary rolling
 - make rolling-${DB}-${YEARMO} $SILENT USER=$USER PASSFLAG= SQLITE=$SQLITE3

after_success:
 - make USER=$USER PASSFLAG= select-$DB

after_failure:
 - head -n 10 sales/raw/20{08,12}-{bronx,brooklyn,manhattan}.csv

addons:
  postgresql: 9.4

matrix:
  allow_failures:
    - env: DB=postgresql

  exclude:
    -
        env: DB=postgresql
        os: osx
    -
        env: DB=sqlite
        os: linux
