os:
 - linux
 - osx

env:
  - DB=mysql
  - DB=sqlite

install:
 - export PATH=$PATH:~/Library/Python/2.7/bin
 - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "mysql" ]]; then brew update > /dev/null; fi
 - if [[ $TRAVIS_OS_NAME == "osx" && $DB == "mysql" ]]; then brew install mysql && mysql.server start; fi
 - make install

before_script:
 - sqlite3 --version

# Broken up like this because travis chokes on the long delete list
# The --silent flags are because travis's on the huge log
# Touch some of the targets because all the downloading is boring
script:
 - make -j2 --silent sales/raw/2004-{bronx,brooklyn,manhattan,queens,statenisland}.xls
 - make -j2 sales/raw/2008-{bronx,brooklyn,manhattan,queens,statenisland}.xls
 - make -j2 --silent sales/raw/2012-{bronx,brooklyn,manhattan,queens,statenisland}.xls
 - make -j2 sales/raw/20{04,08,12}-{bronx,brooklyn,manhattan,statenisland,queens}.csv
 - make --silent $DB USER=root PASSFLAG= YEARS=2004
 - make $DB USER=root PASSFLAG= YEARS=2008
 - make --silent $DB USER=root PASSFLAG= YEARS=2012
 - make YEARS="2004 2008 2012"
 - make USER=root PASSFLAG= select-$DB
 - make -j2 --silent summary rolling

after_failure:
 - head sales/raw/2012-{bronx,brooklyn,manhattan,queens,statenisland}.csv

matrix:
  allow_failures:
    - os: osx
    - env: DB=sqlite
